### ISSUE TITLE
Phone number default region should be customizable

### ISSUE THREAD

**Issue by alekitto** [fazland/fatture-in-cloud-sdk#12]
The phone parser default region is always "IT" as reported in https://github.com/fazland/fatture-in-cloud-sdk/issues/3#issuecomment-494533404

Customization should be implemented [here](https://github.com/fazland/fatture-in-cloud-sdk/blob/ab02ab78daa738809ed095f618bb8c65e9bcda8e/lib/Model/Subject/Subject.php#L152) (possibly with the help of a static property in the Subject model class?)

/cc @alxy

**Comment by dlondero** [comment]
@alekitto as the default region should be the "region that we are expecting the number to be from" would it make sense to simply use `$countryIso` value for that and use `IT` as fallback? I see that `paese_iso` is optional on the API...

**Comment by alekitto** [comment]
I would not relay on `countryIso` field as nothing guarantee that the field will be set before the phone ones.

How about a `$defaultCountryCode` static `?string` field (with static `setDefaultCountryCode` method to set it) and use `static::$defaultCountryCode ?? 'IT'`?

**Comment by alekitto** [comment]
Closed via #25
