### ISSUE TITLE
Add cs lint to pipeline

### ISSUE THREAD

**Issue by alekitto** [fazland/fatture-in-cloud-sdk#19]
Cs check should run on every commit/PR.

GitHub actions should be used to run the linter while travis executes the tests.

**Comment by massimilianobraglia** [comment]
Good point. Just a question: why do you suggest the linter on GitHub Actions and the tests on Travis?

**Comment by alekitto** [comment]
Yes, in order to have separate results the flows need to splitted, otherwise the test build would report an error even if tests are passing but the linter is not. Or, much worse, it will not execute the linter build stage if the tests are not passing.

**Comment by alekitto** [comment]
Closed via #24
