### ISSUE TITLE
Add `giacenza_iniziale` to Good

### ISSUE THREAD

**Issue by alxy** [fazland/fatture-in-cloud-sdk#22]
I am afraid that this is another inconsistency in the API, but I just realized the `Good` class does not contain the `giacenza_iniziale` attribute, which is [documented here](https://api.fattureincloud.it/v1/documentation/dist/#!/Prodotti/ProdottiModifica).

On the other hand, it does contain another attribute `quantita`, which I expect is used in the invoice context (which we do not use). Do you see any issue adding the initial stock attribute to the model class?

**Comment by massimilianobraglia** [comment]
closed by #23
