### ISSUE TITLE
Amount must be an integer(ish) value

### ISSUE THREAD

**Issue by dlondero** [fazland/fatture-in-cloud-sdk#5]
`Document::fromArray` which is called after getting a document or creating a new one (returned value is a new objected created from response in order to have all computed values filled from FIC) is already multiplying `* 100` all amounts to work with integers. This of course is great when working with amounts, also makes happy Money constructor.

Unfortunately FIC api response sends back floats with a precision of 4 digits. Multiplying by 100 does not give us an integer as expected but leaves us a float. Example we get `32.9644` in the response, we multiply `new Money($item['prezzo_netto'] * 100, $this->currency)`, we have now 3296.44 which is passed to Money constructor.

There a `Money\Number` object is created in order to check if the amount passed is an integer or not and unfortunately in our case we still have a decimal part:

```php
if (filter_var($amount, FILTER_VALIDATE_INT) === false) {
    $numberFromString = Number::fromString($amount);
    if (!$numberFromString->isInteger()) {
        throw new \InvalidArgumentException('Amount must be an integer(ish) value');
    }

    $amount = $numberFromString->getIntegerPart();
}
```

This affects only `Document` so far and a quick fix would be to round down amounts to a precision of 2 digits (keeping `PHP_ROUND_HALF_UP` mode) before multiplying by 100:

```php
new Money(round($item['prezzo_netto'], 2) * 100, $this->currency)
```

**EDIT:**
However this approach would work for most cases (currencies with subunits down to cents) it wouldn't work for other cases like `JPY`, `ISK` (just to mention two) without cents or `TND` which goes down to `milim` (1/1000).

Knowing that it would be good to get the `subunit` for a currency in order to know how to round it and how to multiply it to get an integer. Below example:

```php
$eur = new Currency('EUR');
$subUnit = (new ISOCurrencies())->subunitFor($eur);
$amount = new Money(round($item['prezzo_netto'], $subUnit) * (10 ** $subUnit), $this->currency)
```

This would cover all currencies! @alekitto what do you think?

**Comment by alekitto** [comment]
It's ok to check the currencies for subunit digits. My bad at blindly multiplying values by 100..
We probably need a `MoneyUtil` class where this operation can be done.

For the `round` part: while could be done for read-only values, this could lead to inconsistencies or bad calculations if this value will be written to the APIs. Is the `32.9644` value calculated directly from FIC? In which case could be encountered a value like this?

**Comment by dlondero** [comment]
While creating an `Invoice` you can add a product specifying `netPrice` and `vatCode`. Then FIC will compute the `grossPrice` (probably works the other way around if you specify gross prices and set `vatIncluded` to true). In the specific case the amount is 27.02€ which translates to 2702 when creating the `Money` object to assign to `netPrice`, then the values in the response after calling `Invoice::create()` are as follow:

```
[prezzo_netto] => 27.02000
[prezzo_lordo] => 32.96440
```

**Comment by dlondero** [comment]
Should we add then a `MoneyUtil::floatToInteger(float $amount, Currency $currency)`? Naming suggestions are welcome!

**Comment by alekitto** [comment]
Should be fixed in 7ac3809. Please test it and confirm, if possible.
I've added a `PreciseMoney` class to handle subunits and fraction of cents, the signature of all methods are just the same of the `Money` class, but should handle fractions correctly.

**Comment by dlondero** [comment]
Just tested this and works as expected!

I think `MoneyUtil::toMoney` signature could be changed to make `Currency $currency` param mandatory in order to remove the `EUR` fallback which is quite specific and could be avoided imho.

**Comment by alekitto** [comment]
You’re probably right, I was undecided on that. Maybe an exception can be thrown on missing currency (as the amount could be a Money object, the parameter should stay optional).
Anyway, if this issue is resolved, I’m going to close this.
