### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dlondero** [fazland/fatture-in-cloud-sdk#9]
@alekitto Are you planning to add support for all the other end points of the API? Thinking to products, purchases, mail, info, etc... Maybe you could open some issues where to discuss that and then someone could pick up, I could help with that.

**Comment by alekitto** [comment]
Yes, I'll surely begin to implement the other endpoints and resources in the next week.
Also some documentation is needed. I'll open a new issue to keep track of the resources and the endpoints to implement asap.

**Comment by alekitto** [comment]
I've opened #10 to keep track of the resources/endpoints to be implemented in this library. I'm closing this and moving the discussion in the new issue.
